# -*- coding: utf-8 -*-
"""to-do list_codsoft.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c4xrTnt5Rnd0qXYAfefLw4dIQiURFOoX
"""

# here we  have created a To-do LIST by python


# we have classified these tasks
#task list
class Task:
    def __init__(self, name):
        self.name = name
        self.completed = False

    def complete(self):
        self.completed = True

    def __str__(self):
        return self.name
# to do function
#  1.add task
#  2.complete taask
#  3.remove
#  4.print task
class ToDoList:
    def __init__(self):
        self.tasks = []

    def add_task(self, name):
        self.tasks.append(Task(name))

    def complete_task(self, task_name):
        for task in self.tasks:
            if task.name == task_name:
                task.complete()
                break

    def remove_task(self, task_name):
        self.tasks = [task for task in self.tasks if task.name != task_name]

    def print_tasks(self):
        for task in self.tasks:
            print(f"{task.name} {'(completed)' if task.completed else ''}")

# created a main fuction
def main():
    todo_list = ToDoList()
# with  the help of while loop
    while True:
        print("\nTo-Do List")
        print("-----------")
        print("1. Add task")
        print("2. Complete task")
        print("3. Remove task")
        print("4. Print tasks")
        print("5. Quit")

        choice = input("Enter the number of your choice: ")
# here we used strings such as if,elif ,else statement::::
        if choice == '1':
            task_name = input("Enter the name of the task: ")
            todo_list.add_task(task_name)
        elif choice == '2':
            task_name = input("Enter the name of the task to complete: ")
            todo_list.complete_task(task_name)
        elif choice == '3':
            task_name = input("Enter the name of the task to remove: ")
            todo_list.remove_task(task_name)
        elif choice == '4':
            todo_list.print_tasks()
        elif choice == '5':
            break
        else:
            print("Invalid choice. Please try again.")

# created a comandline interface using this
if __name__ == "__main__":
              main()